### ISSUE TITLE
Unknown Crash -- Location: [SA/CSI]

### ISSUE THREAD

**Issue by Fiskey111** [Fiskey111/L.S.Noire#1]
Fatal crash found returning the following error:

`[2016-09-09 10:40:53.210] LSPD First Response: ===== Victim Checked =====
[2016-09-09 10:40:53.213] LSPD First Response: Informed regarding EMS
[2016-09-09 10:40:57.866] LSPD First Response: EMS Called
[2016-09-09 10:40:57.866] LSPD First Response: EMS Transport = False
[2016-09-09 10:41:04.675] LSPD First Response: EvidenceBase.Dismiss: invoked
[2016-09-09 10:41:04.833] LSPD First Response: 
[2016-09-09 10:41:04.834] LSPD First Response: ==============================
[2016-09-09 10:41:04.834] LSPD First Response: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[2016-09-09 10:41:04.834] LSPD First Response: ------------------------------
[2016-09-09 10:41:04.834] LSPD First Response: Origin: Game fiber "<UNNAMED THREAD>".
[2016-09-09 10:41:04.834] LSPD First Response: ------------------------------
[2016-09-09 10:41:04.835] LSPD First Response: Exception type: Rage.Exceptions.InvalidHandleableException
[2016-09-09 10:41:04.835] LSPD First Response: Exception message: Operation is not valid because the specified  Rage.Ped is invalid.
[2016-09-09 10:41:04.835] LSPD First Response: ------------------------------
[2016-09-09 10:41:04.835] LSPD First Response: Inner exceptions:
[2016-09-09 10:41:04.836] LSPD First Response: ------------------------------
[2016-09-09 10:41:04.836] LSPD First Response: Stack trace:
[2016-09-09 10:41:04.836] LSPD First Response: at Rage.Entity.get_Model()
[2016-09-09 10:41:04.836] at ?????????????????????????????????????????.?????????????????????????????????????????(Ped )
[2016-09-09 10:41:04.874] at LSPD_First_Response.Engine.Scripting.Entities.Persona.?????????????????????????????????????????()
[2016-09-09 10:41:04.875] at LSPD_First_Response.Engine.Scripting.Entities.Persona..ctor(Ped ped)
[2016-09-09 10:41:04.875] at ?????????????????????????????????????????..ctor(Ped ped)
[2016-09-09 10:41:04.875] at }_T~83Fsa~MaT7\]O;V!\*j22%$.?????????????????????????????????????????(Ped )
[2016-09-09 10:41:04.875] at LtFlash.Common.EvidenceLibrary.Evidence.Witness.Process()
[2016-09-09 10:41:04.875] at LtFlash.Common.Processes.ProcessHost.Process()
[2016-09-09 10:41:04.875] at LtFlash.Common.Processes.ProcessHost.InternalProcess()
[2016-09-09 10:41:04.875] at Rage.GameFiber.Main()
[2016-09-09 10:41:04.875] LSPD First Response: ==============================
[2016-09-09 10:41:04.875] LSPD First Response: 
[2016-09-09 10:41:05.012] ====================================================================================================
[2016-09-09 10:41:05.012] Unhandled exception occurred in console command "ForceDuty"
[2016-09-09 10:41:05.013] Exception type: System.Threading.ThreadAbortException
[2016-09-09 10:41:05.013] Exception message: Thread was being aborted.
[2016-09-09 10:41:05.013] Stack trace: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
[2016-09-09 10:41:05.013]    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
[2016-09-09 10:41:05.013]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
(...)
[2016-09-09 10:41:05.013]    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
[2016-09-09 10:41:05.013]    at Rage.ConsoleCommands.ConsoleCommand.Execute(Object[] arguments)
[2016-09-09 10:41:05.013]    at Rage.ConsoleCommands.ConsoleCommand.ParseAndExecute(String[] arguments)
[2016-09-09 10:41:05.014]    at Rage.ConsoleCommandGameFiber.Start()
[2016-09-09 10:41:05.014] =====================
[2016-09-09 10:41:05.468] LSPD First Response: EvidenceBase.Dismiss: invoked`

**Comment by Fiskey111** [comment]
*According to Albo1125: "that crash is caused if using an LSPDFR function on an invalid/nonexistent ped"

**Comment by LtFlash** [comment]
Crash is caused by _firstOfficer being disposed by the game. After a task of playing animation is assigned he is taken over by the AI of the game/LSPD:FR and goes away far enough to get removed. That causes LSPD:FR to crash due to an invalid handle.

Commenting out a few lines removes the bug (marked with //FIX: ):
https://github.com/LtFlash/L.S.Noire/commit/817858812679fee7553dbf1ba0ce70b76c425967
