### ISSUE TITLE
LtFlash Common Transport crash -- [SA/CSI]

### ISSUE THREAD

**Issue by Fiskey111** [Fiskey111/L.S.Noire#18]
Transport crashed with following error:

`[17/09/2016 19:45:07.710] LSPD First Response: Transport.SetPedTaskEnter.Beginning
[17/09/2016 19:45:07.743] LSPD First Response: 
[17/09/2016 19:45:07.743] LSPD First Response: ==============================
[17/09/2016 19:45:07.744] LSPD First Response: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[17/09/2016 19:45:07.744] LSPD First Response: ------------------------------
[17/09/2016 19:45:07.744] LSPD First Response: Origin: Game fiber "<UNNAMED THREAD>".
[17/09/2016 19:45:07.744] LSPD First Response: ------------------------------
[17/09/2016 19:45:07.744] LSPD First Response: Exception type: System.NullReferenceException
[17/09/2016 19:45:07.744] LSPD First Response: Exception message: Object reference not set to an instance of an object.
[17/09/2016 19:45:07.744] LSPD First Response: ------------------------------
[17/09/2016 19:45:07.744] LSPD First Response: Inner exceptions:
[17/09/2016 19:45:07.744] LSPD First Response: ------------------------------
[17/09/2016 19:45:07.744] LSPD First Response: Stack trace:
[17/09/2016 19:45:07.744] LSPD First Response: at LtFlash.Common.EvidenceLibrary.Services.Transport.Process()
[17/09/2016 19:45:07.744] at Rage.GameFiber.Main()
[17/09/2016 19:45:07.744] LSPD First Response: ==============================
[17/09/2016 19:45:07.745] LSPD First Response: `

**Comment by LtFlash** [comment]
Fixed.
